package com.timur.enums;

public enum UserState {
    START,

    DEFECTIVE_PRODUCT,
    DEFECTIVE_PRODUCT_Q1,
    DEFECTIVE_PRODUCT_Q2,
    DEFECTIVE_PRODUCT_Q3,

    BUY_PRODUCT,
    BUY_PRODUCT_Q1,

    WHOLESALE_SALES_DEPARTMENT,
    WHOLESALE_SALES_DEPARTMENT_Q1,

    OTHER_QUESTION,
    OTHER_QUESTION_Q1,

    TRANSFER_OPERATOR,
    CONNECT_OPERATOR,

    COMPLETED
}
